config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :breweries
  resources :brewery_login
  resources :products
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :products
  has_secure_password
  validates :email, presence: true

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brewery
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:current_user_id]
      Brewery.find(session[:current_user_id])
    else
      nil
    end
  end
  helper_method :current_user
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController

  def index
  end

  def new
    @brewery = Brewery.new
  end

  def create
    @brewery = Brewery.create(allowed_parameters)
    session[:current_user_id] = @brewery.id
    redirect_to '/products'
  end

  def show
    @brewery = Brewery.find(params[:id])
  end


  private

  def allowed_parameters
    params.require(:brewery).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/brewery_login_controller.rb
class BreweryLoginController < ApplicationController


  def destroy
    @current_user = session[:current_user_id] = nil
    redirect_to root_path
  end

  def new
    @brewery = Brewery.new
  end

  def create
    @brewery = Brewery.find_by(email: params[:brewery][:email]).try(:authenticate, params[:brewery][:password])
    if @brewery
      session[:current_user_id] = @brewery.id
      redirect_to '/products'
    else
      @brewery = Brewery.new
      flash.now[:error] = "User/Password Combination is not correct"
      render :new
    end

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    # if session[:current_user_id]
    #   # @products = Product.find_by()
    # else
      @products = Product.all
    # end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(allowed_parameters)
    if @product.save
      redirect_to '/products', notice: "Product successfully added"
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update_attributes(allowed_parameters)
    redirect_to '/products'
  end

  def destroy
    @product = Product.destroy(params[:id])
    redirect_to '/products'
  end


def allowed_parameters
  params.require(:product).permit(:name, :description, :abv, :image, :brewery_id)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
@current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/breweries/new.html.erb
<div class="authentication_form">
  <h2>Please Register:</h2>

  <ul class="flashes">
    <% @brewery.errors.full_messages.each do |error| %>
      <li class="error"><%= error %></li>
    <% end %>
  </ul>

  <%= form_for @brewery do |b| %>
    <%= b.label :name %>
    <%= b.text_field :name %>
    <%= b.label :email %>
    <%= b.email_field :email %>
    <%= b.label :password %>
    <%= b.password_field :password %>
    <%= b.label :password_confirmation %>
    <%= b.password_field :password_confirmation %>
    <%= b.submit "Submit" %>
  <% end %>
</div>

app/views/brewery_login/new.html.erb
<div class="authentication_form">
  <h2>Please Login:</h2>

  <ul class="flashes">
    <% @brewery.errors.full_messages.each do |error| %>
      <li class="error"><%= error %></li>
    <% end %>
  </ul>

  <%= form_for @brewery do |b| %>
    <%= b.label :email %>
    <%= b.email_field :email %>
    <%= b.label :password %>
    <%= b.password_field :password %>
    <%= b.submit "Submit" %>
  <% end %>
  <h3><%= link_to 'Click here to register', new_brewery_path %></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Growlers to Go</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="UTF-8">
  <title>Growlers To Go</title>
  <link href="style.css" rel="stylesheet" type="text/css"/>
  <link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css">
  <link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/bootstrap.css">
  <link rel="stylesheet" href="main.css">

</head>

<body>
<div class="nav">
  <div class="container">
    <ul class="pull-left">
      <li><a href="/">Growlers to Go</a></li>
    </ul>
    <ul class = "pull-right">
      <% if current_user %>
        <li><a href="#">Welcome, <%= current_user.email %></a></li>
        <li><a href='/products'>View Products</a></li>
        <li><a href='/products/new'>Add Products</a></li>

        <li><%= link_to 'Logout', brewery_login_path(current_user.id), method: :delete %></li>
      <% else %>
        <li><%= link_to 'Brewery Login', new_brewery_login_path %></li>
      <% end %>

    </ul>
  </div>
</div>
<div class="jumbotron">
  <div class="container">
    <h1>Growlers to Go</h1>

  </div>
</div>


<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<div class="authentication_form">
  <h2>Edit Product:</h2>

  <%= form_for @product do |p| %>
    <ul class="flashes">
      <% @product.errors.full_messages.each do |error| %>
        <li class="error"><%= error %></li>
      <% end %>
    </ul>
    <%= p.label :name %>
    <%= p.text_field :name, value: @product.name %>
    <%= p.label :description %>
    <%= p.text_area :description, :size =>"72x10", :length => 500, value: @product.description %>
    <%= p.label :abv %>
    <%= p.text_field :abv, value: @product.abv %>
    <%= p.file_field :image %>
    <%= p.label :remote_image_url, "or image url" %>
    <%= p.text_field :remote_image_url %>
    <%= p.submit 'Submit' %>
  <% end %>
  <%= link_to 'Delete', product_path(@product), method: :delete %>
</div>

app/views/products/index.html.erb
<div class="content_container">
  <p class="flash_notice"><%= flash[:alert] %></p>

  <% @products.each do |product| %>
    <div class="product_container">
      <div class="product_picture_small">
        <%= image_tag product.image.to_s %>
      </div>
      <!--end product_picture-->

      <div class="product_description">
        <li>
          <%= link_to product.name, product_path(product.id) %>
        </li>
        <li>
          <%= product.description %>
        </li>
        <li>
          <%= product.abv %>
        </li>

      </div>
      <!--end product_description-->
    </div>

    <!--end product_container-->
  <% end %>
</div><!--end content_container-->

app/views/products/new.html.erb
<div class="authentication_form">
  <h2>Add Beer:</h2>

  <%= form_for @product, :html => {:multipart => true} do |p| %>
  <ul class="flashes">
    <% @product.errors.full_messages.each do |error| %>
      <li class="error"><%= error %></li>
    <% end %>
  </ul>

    <%= p.label :brewery_id, 'Brewery' %>
    <%= p.select :brewery_id, Brewery.all.map { |brewery| [brewery.name, brewery.id] },
                 :include_blank => 'Select a brewery' %>

    <%= p.label :name %>
    <%= p.text_field :name %>

    <%= p.label :description %>
    <%= p.text_area :description, :size =>"72x10", :length => 500 %>

    <%= p.label :abv %>
    <%= p.text_field :abv %>

    <%= p.file_field :image %>


    <%= p.label :remote_image_url, "or image url" %>
    <%= p.text_field :remote_image_url %>

    <%= p.submit 'Submit' %>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="product_container">
  <div class="product_picture_large">
    <img src="<%= @product.image %>">
  </div>
  <!--end product_picture-->
  <div class="product_description">
    <li>
      <%= @product.name %>
    </li>
    <li>
      <%= @product.description %>
    </li>
     <li><%= @product.abv %></li>
    <a href="/products/<%= @product.id %>/edit">Edit</a>


  </div>
  <!--end product_description-->
</div>
<!--end product_container-->

app/views/welcome/index.html.erb
<!doctype html>


<html>
<head>

</head>

<header>
</header>


<body>

<div class="featured-breweries">
  <div class="container">
    <h2>Featured Breweries</h2>
    <h2>Growlers to Go delivers fresh beer directly from local breweries to your front door.</h2>
    <div class="row">
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="http://beerindenver.com/wp-content/uploads/2013/02/Boulder-Beer.jpg">
        </div>
        <div class="thumbnail">
          <img src="http://upslopebrewing.com/wp-content/uploads/2014/03/upslope-logo-1-red.jpg">
        </div>
      </div>
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="http://upload.wikimedia.org/wikipedia/en/8/8b/Avery_Brewing_Company_logo.jpg">
        </div>
        <div class="thumbnail">
          <img src="http://www.firstbiteboulder.com/uploaded-files/logos/Fate-Brewing-Co-Full%20Logo_121212-075518.jpg">
        </div>
      </div>
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="http://theroamingpint.com/wp-content/uploads/2011/09/mountain_sun_logo_000.jpg">
        </div>
      </div>
    </div>
  </div>
</div>
<div class="learn-more">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h3>Membership</h3>
        <p>Monthly memberships start at only $79</p>
        <p><a href="#">Click here to join!</a></p>
      </div>
      <div class="col-md-4">
        <h3>TBD</h3>
        <p>Something more to come here</p>
        <p><a href="#">Learn more about hosting</a></p>
      </div>
    </div>
  </div>
</div>

</body>
</html>